[[assertions]]
Summary of Assertions
---------------------

Controller methods are JAX-RS resource methods annotated with . All
resource methods in a class annotated with must be controllers.
Controller methods that return void must be annotated with . MVC beans
are managed by CDI. Default scope for MVC beans is request scope. If
validation fails, controller methods must still be called if a field or
property is defined. All events in must be fired. See Javadoc for more
information on each event in that package. Implementations must provide
support for JSPs and Facelets. CDI beans that implement provide an
extension mechanism for view engines. Implementations must use algorithm
in Section [selection_algorithm] to select view engines. Forward request
for which no view engine is found. Exceptions thrown during view
processing must be wrapped. Relative paths to views must be resolved as
explained in Section [selection_algorithm]. The annotation is treated as
a default value for any controller method that returns a value. Support
HTTP redirects using the redirect: prefix and a controller return type
of String. Annotation inheritance is derived from   and extended to
 annotations. CSRF support for configuration options defined by
Csrf.CsrfOptions. CSRF validation required only for controllers
annotated by @POST and consuming the media type x-www-form-urlencoded.
Application-scoped MvcContext available for injection and as mvc in EL.
The must provide access to the current request locale. CDI beans
implementing provide an extension mechanism for the request locale
resolving algorithm. The request locale must be resolved as described in
Section [i18n_resolving_algorithm]. Implementations must provide a
default locale resolver as described in Section [i18n_default_resolver].
